### ISSUE TITLE
Error:  ./stack.sh:235 If you wish to run this script anyway run with FORCE=yes

### ISSUE THREAD

**Issue by Jagadeeshftw** [EmilienM/devstack-action#16]
Job link:
https://github.com/Jagadeeshftw/Docker-CICD/actions/runs/7513108110/job/20454500831
My workflow file:
```
name: Openstack Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.6
        with:
          branch: stable/xena
          conf_overrides:
            CINDER_ISCSI_HELPER=tgtadm
          enabled_services: 's-account,s-container,s-object,s-proxy'
```
